- name: disbale nodejs service
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable nodejs20 service
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install nodejs and mysql service
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: 
    - mysql
    - nodejs 

- name: create user expense
  ansible.builtin.user:
    name: expense

- name: import tasks from common role
  tags:
  - deployment
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

- name: download the dependency
  tags:
  - deployment
  ansible.builtin.command: npm install
  args:
    chdir: /app

- name: copy the backend service file
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service

- name: install the pip dependencies
  ansible.builtin.pip:
    name: 
      - PyMySQL
      - cryptography
    executable: pip3.9

- name: import of sql data
  community.mysql.mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: "{{ login_host }}"
    target: /app/schema/backend.sql
    state: import
    name: all

- name: daemon reload
  tags:
  - deployment
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: backend
    enabled: true
